x-gust-env: &gust-env
  B64_SECRETS_CLOAK_KEY: ADD_HERE_AS_BASE64 # WARNING: generate using `openssl rand -base64 32`
  SECRET_KEY_BASE: ADD_HERE_SECRET_KEY_BASE # WARNING: generate using `mix phx.gen.secret`, or `openssl rand -hex 32` if you don't have a Phoenix project
  DATABASE_URL: "ecto://gust:gust@db:5432/gust_prod"
  POOL_SIZE: "10"
  RELEASE_COOKIE: "gust_secret_cookie_123"
  DNS_CLUSTER_QUERY: "gust,gust-web"

x-gust-web-env: &gust-web-env
  PHX_SERVER: "true"
  PHX_HOST: "localhost"
  PORT: "4000"
  BASIC_AUTH_USER: admin # WARNING: change before deploying to production
  BASIC_AUTH_PASS: admin # WARNING: change before deploying to production

x-gust-depends-on-db: &gust-depends-on-db
  depends_on:
    db:
      condition: service_healthy

x-gust-volumes: &gust-volumes
  volumes:
    - ./dags:/dags # WARNING: Make sure you have a /dags folder

services:
  db:
    image: postgres:16-alpine
    container_name: postgres_gust_db
    environment:
      POSTGRES_USER: gust
      POSTGRES_PASSWORD: gust
      POSTGRES_DB: gust_prod
    ports:
      - "5432:5432"
    volumes:
      - gust_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U gust -d gust_prod"]
      interval: 5s
      timeout: 3s
      retries: 20

  gust-init:
    image: marcioklepacz/gust-web:0.1.32
    <<: *gust-depends-on-db
    command: ["/app/bin/migrate"]
    restart: "no"
    environment:
      <<: [*gust-env, *gust-web-env]
      PHX_SERVER: "false"
      GUST_ROLE: core

  gust:
    image: marcioklepacz/gust:0.1.32
    <<: [*gust-depends-on-db, *gust-volumes]
    command: ["/app/bin/start-core"]
    environment:
      <<: *gust-env
      GUST_ROLE: core
      PHX_SERVER: "false"

  gust-web:
    image: marcioklepacz/gust-web:0.1.32
    <<: [*gust-depends-on-db, *gust-volumes]
    ports:
      - "4000:4000"
    command: ["/app/bin/server"]
    environment:
      <<: [*gust-env, *gust-web-env]
      GUST_ROLE: web

volumes:
  gust_pgdata:
