name: Test

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    env:
      MIX_ENV: test
      PGUSER: postgres
      PGPASSWORD: postgres
      PGHOST: localhost
      PGPORT: 5432
      B64_SECRETS_CLOAK_KEY: PF4/V7ZLI8Nyjymua0eUy2K8q/lcSFi3USe3UUDb7sY=
      SECRET_KEY_BASE: dWKtgAuY24rgqDQCLkN9S5CaOqSFzdrnqO4iHqVlIp5uLQPB6MjVJqlEN7w1nOvX

    services:
      postgres:
        image: postgres:14
        ports: ['5432:5432']
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: '1.18'
          otp-version: '27.0'

      - name: Restore dependencies cache
        uses: actions/cache@v3
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-mix-

      - name: Install deps
        run: mix deps.get

      - name: Install asset tools
        run: |
          npm install --prefix apps/gust_web/assets
          mix tailwind.install
          mix esbuild.install

      - name: Build assets
        run: |
          mix assets.build

      - name: Compile without errors
        run: |
          mix compile --warnings-as-errors

      - name: Check formatting
        run: mix format --check-formatted

      - name: Run lint
        run: mix lint

      - name: Create and migrate DB
        run: |
          mix ecto.create
          mix ecto.migrate

      - name: Run tests
        run: mix coveralls.json --umbrella

      - name: Coveralls
        uses: coverallsapp/github-action@v2
        with: 
          file: cover/excoveralls.json 
